name: generate poadcast feed

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chekout repo
        uses: actions/checkout@v3
      - name: Run Feed Generator 
        uses: rosepate/poadcast-generator@main
        
